# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build the TypeScript source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Run the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
